title: Hafsa Habib # your name (or website title) here
logo: "/images/hafsa_logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A few years ago, I obtained Machine Learning and Deep Learning Nanodegrees from Coursera, and have quickly become an expert in 
  Neural Networks and Computer Vision.
  I use Python, Keras, and Tensorflow to train my Deep Neural Networks, and 
  analyze the data using Python, Numpy, Pandas, Scikit Learn, Matplotlib, etc...

  <br><br>
Areas of interest include 
Digital Image Processing,
Speech Processing,
Computer Vision,
Signal Analysis,
Algorithms,
Chatbots,
Voice Recognition,
NLP, and
Object Detection
  <br><br>
  <a href="https://www.linkedin.com/in/hafsa-bukhary-aa5376118/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
//google_analytics: UA-000000-0 # your Google Analytics tracking ID here
