title: Hafsa Habib # your name (or website title) here
logo: "/images/hafsa_logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Python| Data Science & Machine Learning| Educator
  <br>
 
  <br>
 
  <a href="https://www.linkedin.com/in/hafsa-bukhary-aa5376118/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
//google_analytics: UA-000000-0 # your Google Analytics tracking ID here
